### ISSUE TITLE
Unattended install

### ISSUE THREAD

**Issue by worldofgeese** [Linux-Is-Best/Firefox-automatic-install-for-Linux#10]
I have a script I use on new computers intended to be run unattended. The script allows passwordless elevation of user privileges. It would be great to have a `bash Setup.sh -y` option that fetches the latest stable Firefox release and installs without prompt.

**Comment by Linux-Is-Best** [comment]
The OEM folder would overall fit your needs.  `bash firefox_stable.sh`  but it would need to be run with root type privileges. That's because to set up Firefox on your system, you still cannot overcome the new to set the correct permissions and apply (install) the shortcuts when needed.  Once installed, each user already had their own (individual) profile too (located in their home folder).

I suspect you want a script that works for you and only you. For that, download Firefox, and extract it anywhere in your home folder. No root privileges required and no password needed.  But then, of course, the only place you could put a shortcut would be the desktop.

**Comment by Linux-Is-Best** [comment]
OK, this example should work for a personal install. Installing everything into the user's home directly.  I used Firefox Nightly for my example.  You will also need to edit the shortcuts to match the correct path (which I did not include in my example, only the install).

`#!/bin/bash
wget -O FirefoxNightly.tar.bz2 "https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64";
mkdir -p -m 755 /home/$USER/Mozilla ;
mkdir /home/$USER/Mozilla/firefox-nightly ;
tar xjf FirefoxNightly.tar.bz2 -C /home/$USER/Mozilla/firefox-nightly/ ;
chmod -R 757 /home/$USER/Mozilla/firefox-nightly/firefox/ ;
chmod +x ./fn64-icon.sh ; bash ./fn64-icon.sh ;
sleep 2;
chmod +x Firefox-Nightly.desktop ;
cp Firefox-Nightly.desktop /home/$USER/.local/share/applications/ ;
for destdir in /home/$USER/Desktop/; do
    cp Firefox-Nightly.desktop "$destdir" &&
    chown --reference="$destdir" "$destdir/Firefox-Nightly.desktop"
done
echo -n;
rm FirefoxNightly.tar.bz2 ; rm Firefox-Nightly.desktop ;
exit 0`

**Comment by Linux-Is-Best** [comment]
I don't particularly appreciate how Github formatted the layout, so here is the sh file.  Again, you will still need to edit the shortcuts (I only made the install for you).
[custom_request.zip](https://github.com/Linux-Is-Best/Firefox-automatic-install-for-Linux/files/6642627/custom_request.zip)

**Comment by Linux-Is-Best** [comment]
OK, your inquire has caused me to develop a personal installer for the next release. Not everyone is the system administrator (obviously) but may wish to use Mozilla Firefox. And not everyone may wish to install Mozilla Firefox for everyone (although I cannot imagine why). So here I am, working on expanding the installer for people such as yourself. lol

**Comment by Linux-Is-Best** [comment]
New release https://github.com/Linux-Is-Best/Firefox-automatic-install-for-Linux/releases/tag/2.8.0
